//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZSGameEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZSGameEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is expected to be an instance of the type &apos;Type&apos; or &apos;Guid&apos;..
        /// </summary>
        internal static string ArgumentExceptionMessageParameter {
            get {
                return ResourceManager.GetString("ArgumentExceptionMessageParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add child element.
        /// </summary>
        internal static string ContextMenuAddChildText {
            get {
                return ResourceManager.GetString("ContextMenuAddChildText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete element.
        /// </summary>
        internal static string ContextMenuDeleteText {
            get {
                return ResourceManager.GetString("ContextMenuDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlEditorContextMenu.
        /// </summary>
        internal static string ContextMenuName {
            get {
                return ResourceManager.GetString("ContextMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewAttribute.
        /// </summary>
        internal static string DefaultAttributeName {
            get {
                return ResourceManager.GetString("DefaultAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewChildNode.
        /// </summary>
        internal static string DefaultChildName {
            get {
                return ResourceManager.GetString("DefaultChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [Design].
        /// </summary>
        internal static string EditorCaption {
            get {
                return ResourceManager.GetString("EditorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeViewEditorPane.
        /// </summary>
        internal static string EditorPaneName {
            get {
                return ResourceManager.GetString("EditorPaneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing source XML.
        /// </summary>
        internal static string ErrorParsingSourceXML {
            get {
                return ResourceManager.GetString("ErrorParsingSourceXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory type can not be null..
        /// </summary>
        internal static string ExceptionMessageNullFactoryType {
            get {
                return ResourceManager.GetString("ExceptionMessageNullFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not a valid PropertyChangeAction.
        /// </summary>
        internal static string ExceptionMessageWrongAction {
            get {
                return ResourceManager.GetString("ExceptionMessageWrongAction", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap i0 {
            get {
                object obj = ResourceManager.GetObject("i0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Images_32bit {
            get {
                object obj = ResourceManager.GetObject("Images_32bit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tree node label.
        /// </summary>
        internal static string InvalidNodeName {
            get {
                return ResourceManager.GetString("InvalidNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Name cannot be blank.
        /// </summary>
        internal static string InvalidNodeNameEmpty {
            get {
                return ResourceManager.GetString("InvalidNodeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label edit error.
        /// </summary>
        internal static string MessageBoxCaptionLabelEditError {
            get {
                return ResourceManager.GetString("MessageBoxCaptionLabelEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factoryType.
        /// </summary>
        internal static string ParameterNameFactoryType {
            get {
                return ResourceManager.GetString("ParameterNameFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string ShowPropertiesText {
            get {
                return ResourceManager.GetString("ShowPropertiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showPropertiesToolStripMenuItem.
        /// </summary>
        internal static string ShowPropertiesToolStripMenuItem {
            get {
                return ResourceManager.GetString("ShowPropertiesToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusMessageLabel.
        /// </summary>
        internal static string StatusMessageLabelName {
            get {
                return ResourceManager.GetString("StatusMessageLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlTreeViewEditor.
        /// </summary>
        internal static string TreeViewEditorControlName {
            get {
                return ResourceManager.GetString("TreeViewEditorControlName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap xmlatt {
            get {
                object obj = ResourceManager.GetObject("xmlatt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Attributes Collection].
        /// </summary>
        internal static string XmlAttributesTypeString {
            get {
                return ResourceManager.GetString("XmlAttributesTypeString", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap xmlerr {
            get {
                object obj = ResourceManager.GetObject("xmlerr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xmlgrp {
            get {
                object obj = ResourceManager.GetObject("xmlgrp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xmlnode {
            get {
                object obj = ResourceManager.GetObject("xmlnode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap xmlval {
            get {
                object obj = ResourceManager.GetObject("xmlval", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
